- name: variables
  hosts: localhost
  vars: 
    course: "terraform"
    trianer: "sivakumar"
    duration: "120hrs"
  tasks: 
  - name: print override information
    vars:
      course:  "AWS"
    ansible.builtin.debug:
      msg: "hi iam learning {{course}} course from trainer {{trainer}} duration is {{durtaion}}."

 - name: print information
   ansible.builtin.debug:
     msg: "hi iam learning {{course}} course from trainer {{trainer}} duration is {{durtaion}}."

  
