- name: variables preferences
  hosts: localhost
  vars:
    WISHES: "morning from PLAY variable"
  vars_files:
  - vars.yaml
  vars_prompt:
  - name: NAME
    prompt: please enter NAME 
    private: False
  - name: WISHES
    prompt: please enter WISHES  
    private: False 
  tasks:
  - name: vars from preferences
    vars:
      NAME: "sridevi from tasks"
      WISHES: "morning from sridevi tasks"
    ansible.builtin.debug:
      msg: "hi hello {{NAME}}, Good {{WISHES}} to you."
