- name: data types
  hosts: localhost
  vars:
    Course: AWSDEVOPS
    Tools:
    - Linux
    - Aws
    - Terraform
    Experience: 
      Devops: 1
      Linux: 2
      Aws: 3
    Realtimeproject: true
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "started course {{Course}}, with these {{Tools}}, for exp {{Experience}}, it is a realtime project{{Realtimeproject}}." 