---
- name: securely cp the pem file in servers
  hosts: PROD
  become: yes
  tasks: 
    - name: copy the pem to servers
      ansible.builtin.copy:
        src: /home/ec2-user/.ssh/deps.pem
        dest: /home/ec2-user/deps.pem
        owner: ec2-user
        group: ec2-user
        mode: '0400'
      vars: 
         ansible_become_password: "{vault_become_password | default('') }}"    
      
      
      


    

